name: Velmie
description: Velmie wallet project

version: 1.2.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: 3.14.0

  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.0
  fluttertoast: 7.1.1
  flutter_svg: 0.19.1
  meta: 1.3.0-nullsafety.3
  equatable: 1.2.5
  flutter_secure_storage: 3.3.5
  provider: 4.3.2+2
  shimmer: 1.1.2
  permission_handler: 5.0.1+2
  contacts_service: 0.4.6
  logger: 0.9.4
  dio: 3.0.10
  carousel_slider: 2.3.1
  get: 2.14.1
  flutter_bloc: 6.1.1
  barcode_scan: 3.0.1
  qr_flutter: 3.2.0
  esys_flutter_share: 1.0.2
  image_gallery_saver: 1.6.1
  pull_to_refresh: 1.6.2
  flutter_masked_text: 0.8.0
  image_picker: 0.6.7+12
  api_error_parser: 0.0.5
  network_utils: 0.0.3
  intl: 0.16.1
  firebase_messaging: 6.0.16
  flutter_udid: 1.0.1
  screenshot: 0.2.0
  custom_refresh_indicator: 0.9.0
  url_launcher: 5.7.10
  flutter_image_compress: 0.7.0
  flutter_screenutil: 2.1.0
  easy_localization: 2.3.3
  easy_localization_loader:
    git:
      url: git://github.com/DmitryM9/easy_localization_loader.git
      ref: overman-dev
  local_auth: 0.6.3+3
  page_view_indicators: 1.4.0
  modal_bottom_sheet: 0.2.2
  flutter_sim_country_code: 0.0.3
  package_info: 0.4.3
  device_info: ^1.0.0
  camera: 0.7.0+2
  path_provider: 1.6.21
  formz: 0.3.2
  native_pdf_view: ^3.9.0
  flutter_inappwebview: 4.0.0+4
  ext_storage: ^1.0.3
  multi_select_flutter: ^3.1.8
  flutter_datetime_picker: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

# To generate icons run:
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/strings/
    - assets/images/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Regular.ttf
        - asset: assets/fonts/HelveticaNeue-Bold.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
